platform :ios, '10.0'
inhibit_all_warnings!

target 'JFJExtension_Example' do
  pod 'JFJExtension', :path => '../'

  target 'JFJExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
