use_frameworks!

target 'JFJExtension_Example' do
  pod 'JFJExtension', :path => '../'

  target 'JFJExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
